# Data Structures

## Data structures: The maintanence, management, and arangment of data.

- Structures:
    - Linear:  sequentially 
    - Non-linear: Correlated, but not in an oredered format

- Linear:
    - List
    - Array
    - Tuple
    - Dict
    - Set

### Array - Matrix operations and statistics

In [15]:
import numpy as np

array = np.array([[2, 4], [6, 8]])
array_2 = np.array([[3, 5], [5, 3]])

In [29]:
mean = np.mean(array)

product = np.dot(array, array_2)

print(f'Mean: {mean}')
print(f'Product: {product}') 

Mean: 5.0
Product: [[26 22]
 [58 54]]


In [45]:
# 3x3 matrix
array_3 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])

array_3

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [47]:
# Transpose
array_3_transpose = array_3.T

array_3_transpose

array([[ 2,  8, 14],
       [ 4, 10, 16],
       [ 6, 12, 18]])

In [55]:
# Dot product
array_3_product = np.dot(array_3, array_3_transpose)

array_3_product

array([[ 56, 128, 200],
       [128, 308, 488],
       [200, 488, 776]])

### List

In [66]:
# Largest value from list
l1 = [12, 34, 85, 43, 56, 86, 54, 22]

print(max(l1))
print(min(l1))

86
12


In [70]:
# Reverse

l1_rev = l1[::-1]

l1_rev

[22, 54, 86, 56, 43, 85, 34, 12]

In [74]:
# Number of times apple appears
l2 = ['apple', 'kiwi', 'kiwi', 'banana', 'apple', 'apple']

l2.count('apple')

3

In [80]:
# Number of imes each word appears
for i in np.unique(l2):
    count = l2.count(i)
    print(f'{i}: {count}')

apple: 3
banana: 1
kiwi: 2
